GET http://localhost:3000/contacts

###
POST http://localhost:3000/contacts
content-type: application/json

{
  "first_name": "Stassie",
  "last_name": "Shimizu", 
  "email": "stassie.shimizu@gmail.com",
  "phone_number": "1234567890",
  "address": "Las Vegas"
}

###
GET http://localhost:3000/contacts/52

###
PATCH http://localhost:3000/contacts/50
content-type: application/json

{
  "first_name": "Stassie",
  "last_name": "Shimizu", 
  "email": "stassie.shimizu@gmail.com",
  "phone_number": "1234567890",
  "address": "Las Vegas"
}

###
DELETE http://localhost:3000/contacts/50