GET http://localhost:3000/contacts

###
POST http://localhost:3000/contacts
content-type: application/json

{
  "first_name": "Leon",
  "last_name": "Shimizu", 
  "email": "lmshimizu@gmail.com",
  "phone_number": "1234567890",
  "address": "Sinajana GU"
}

###
GET http://localhost:3000/contacts/63

###
PATCH http://localhost:3000/contacts/54
content-type: application/json

{
  "first_name": "Anastasia",
  "last_name": "Shimizu", 
  "email": "stassie.shimizu@gmail.com",
  "phone_number": "1234567890",
  "latitude": 50.5,
  "longitude": 20.8
}

###
DELETE http://localhost:3000/contacts/50